package com.example.util

import com.example.data.model.AiTranscript
import com.example.data.model.AiTranscriptSegment
import java.util.regex.Pattern

object TranscriptParser {

    /**
     * Parses SRT or WebVTT content and returns a structured AiTranscript.
     */
    fun parse(content: String, language: String = "fr"): AiTranscript {
        val segments = mutableListOf<AiTranscriptSegment>()
        
        // Normalize line endings
        val lines = content.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        
        var currentStart = -1.0
        var currentEnd = -1.0
        val currentText = StringBuilder()
        
        // Regular expressions for SRT & WebVTT time stamps
        // e.g., 00:01:20,123 --> 00:01:23,456 or 00:00.000 --> 00:03.120
        val timePattern = Pattern.compile("(\\d{2}):(\\d{2}):(\\d{2})[.,](\\d{3})\\s*-->\\s*(\\d{2}):(\\d{2}):(\\d{2})[.,](\\d{3})")
        val shortTimePattern = Pattern.compile("(\\d{2}):(\\d{2})[.,](\\d{3})\\s*-->\\s*(\\d{2}):(\\d{2})[.,](\\d{3})")

        for (line in lines) {
            val trimmedLine = line.trim()
            if (trimmedLine.isEmpty()) {
                if (currentStart >= 0 && currentText.isNotEmpty()) {
                    segments.add(AiTranscriptSegment(
                        startTime = currentStart,
                        endTime = currentEnd,
                        text = currentText.toString().trim()
                    ))
                    currentStart = -1.0
                    currentEnd = -1.0
                    currentText.clear()
                }
                continue
            }

            // Check if line contains timestamp
            val matcher = timePattern.matcher(trimmedLine)
            val shortMatcher = shortTimePattern.matcher(trimmedLine)
            
            if (matcher.find()) {
                // If there's pending segment, push it
                if (currentStart >= 0 && currentText.isNotEmpty()) {
                    segments.add(AiTranscriptSegment(
                        startTime = currentStart,
                        endTime = currentEnd,
                        text = currentText.toString().trim()
                    ))
                    currentText.clear()
                }
                
                currentStart = parseToSeconds(
                    matcher.group(1)!!.toInt(),
                    matcher.group(2)!!.toInt(),
                    matcher.group(3)!!.toInt(),
                    matcher.group(4)!!.toInt()
                )
                currentEnd = parseToSeconds(
                    matcher.group(5)!!.toInt(),
                    matcher.group(6)!!.toInt(),
                    matcher.group(7)!!.toInt(),
                    matcher.group(8)!!.toInt()
                )
            } else if (shortMatcher.find()) {
                if (currentStart >= 0 && currentText.isNotEmpty()) {
                    segments.add(AiTranscriptSegment(
                        startTime = currentStart,
                        endTime = currentEnd,
                        text = currentText.toString().trim()
                    ))
                    currentText.clear()
                }
                
                currentStart = parseShortToSeconds(
                    shortMatcher.group(1)!!.toInt(),
                    shortMatcher.group(2)!!.toInt(),
                    shortMatcher.group(3)!!.toInt()
                )
                currentEnd = parseShortToSeconds(
                    shortMatcher.group(4)!!.toInt(),
                    shortMatcher.group(5)!!.toInt(),
                    shortMatcher.group(6)!!.toInt()
                )
            } else {
                // It's text or segment number
                if (trimmedLine.matches(Regex("\\d+")) && currentStart < 0) {
                    // Skip SRT segment numbers if not in a segment
                    continue
                }
                if (trimmedLine.equals("WEBVTT", ignoreCase = true)) {
                    continue
                }
                
                if (currentStart >= 0) {
                    if (currentText.isNotEmpty()) currentText.append(" ")
                    currentText.append(trimmedLine)
                }
            }
        }
        
        // Catch final segment if any
        if (currentStart >= 0 && currentText.isNotEmpty()) {
            segments.add(AiTranscriptSegment(
                startTime = currentStart,
                endTime = currentEnd,
                text = currentText.toString().trim()
            ))
        }

        return AiTranscript(
            language = language,
            isAutoGenerated = content.contains("auto-generated", ignoreCase = true),
            segments = segments
        )
    }

    private fun parseToSeconds(h: Int, m: Int, s: Int, ms: Int): Double {
        return h * 3600.0 + m * 60.0 + s + (ms / 1000.0)
    }

    private fun parseShortToSeconds(m: Int, s: Int, ms: Int): Double {
        return m * 60.0 + s + (ms / 1000.0)
    }
}
