package com.example.data.model

import org.json.JSONArray
import org.json.JSONObject

data class AiMediaContext(
    val mediaId: String,
    val title: String,
    val creator: String,
    val platform: String,
    val description: String,
    val duration: Long, // in seconds
    val existingTags: List<String> = emptyList(),
    val transcript: String? = null,
    val subtitleLanguage: String? = null,
    val userNotes: String? = null
)

data class AiChapter(
    val startTimestamp: Long, // in seconds
    val title: String,
    val shortDescription: String
) {
    fun toJsonObject(): JSONObject {
        return JSONObject().apply {
            put("startTimestamp", startTimestamp)
            put("title", title)
            put("shortDescription", shortDescription)
        }
    }

    companion object {
        fun fromJsonObject(obj: JSONObject): AiChapter {
            return AiChapter(
                startTimestamp = obj.getLong("startTimestamp"),
                title = obj.getString("title"),
                shortDescription = obj.getString("shortDescription")
            )
        }
        
        fun listToJsonString(chapters: List<AiChapter>): String {
            val arr = JSONArray()
            chapters.forEach { arr.put(it.toJsonObject()) }
            return arr.toString()
        }

        fun listFromJsonString(jsonStr: String?): List<AiChapter> {
            if (jsonStr.isNullOrBlank()) return emptyList()
            try {
                val arr = JSONArray(jsonStr)
                val list = mutableListOf<AiChapter>()
                for (i in 0 until arr.length()) {
                    list.add(fromJsonObject(arr.getJSONObject(i)))
                }
                return list
            } catch (_: Exception) {
                return emptyList()
            }
        }
    }
}

data class AiTranscriptSegment(
    val startTime: Double, // in seconds
    val endTime: Double, // in seconds
    val text: String
) {
    fun toJsonObject(): JSONObject {
        return JSONObject().apply {
            put("startTime", startTime)
            put("endTime", endTime)
            put("text", text)
        }
    }

    companion object {
        fun fromJsonObject(obj: JSONObject): AiTranscriptSegment {
            return AiTranscriptSegment(
                startTime = obj.getDouble("startTime"),
                endTime = obj.getDouble("endTime"),
                text = obj.getString("text")
            )
        }
    }
}

data class AiTranscript(
    val language: String,
    val isAutoGenerated: Boolean = false,
    val segments: List<AiTranscriptSegment>
) {
    fun toJsonString(): String {
        return JSONObject().apply {
            put("language", language)
            put("isAutoGenerated", isAutoGenerated)
            val arr = JSONArray()
            segments.forEach { arr.put(it.toJsonObject()) }
            put("segments", arr)
        }.toString()
    }

    companion object {
        fun fromJsonString(jsonStr: String?): AiTranscript? {
            if (jsonStr.isNullOrBlank()) return null
            try {
                val obj = JSONObject(jsonStr)
                val lang = obj.getString("language")
                val isAuto = obj.optBoolean("isAutoGenerated", false)
                val arr = obj.getJSONArray("segments")
                val segments = mutableListOf<AiTranscriptSegment>()
                for (i in 0 until arr.length()) {
                    segments.add(AiTranscriptSegment.fromJsonObject(arr.getJSONObject(i)))
                }
                return AiTranscript(lang, isAuto, segments)
            } catch (_: Exception) {
                return null
            }
        }
    }
}
